import { strict as assert } from 'node:assert'
import { describe, it } from 'node:test'
import { derivePublicKeyBase64, generateKeypair } from '@/vault/keypair'

// Keypair import covers the cryptographic boundary used by private-key account import.
describe('derivePublicKeyBase64', () => {
  it('derives the public key for an imported private key', async () => {
    // Scenario: an imported party only provides the private key, so the wallet must derive the
    // public key used by provider payloads from that same secret.
    const keypair = await generateKeypair()

    // Action: derive the public key from the imported private key hex.
    const derived = await derivePublicKeyBase64(keypair.privateKeyHex)

    // Expected result: the derived public key matches the keypair generated by the wallet.
    assert.equal(derived, keypair.publicKeyBase64)
  })

  it('rejects malformed imported private keys before vault mutation', async () => {
    // Scenario: import should fail before addAccount when the private key is not valid hex.
    const invalidPrivateKey = 'not-hex'

    // Expected result: malformed input is reported as an invalid private key.
    await assert.rejects(() => derivePublicKeyBase64(invalidPrivateKey), /invalid private key/i)
  })
})
