_storage {
  type = postgres
  config {
    dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
    properties = {
      serverName = ${DB_SERVER}
      portNumber = 5432
      user = ${DB_USER}
      password = ${DB_PASSWORD}
      tcpKeepAlive = true
    }
  }
  parameters {
    max-connections = 16
    migrate-and-start = true
  }
}

canton {
  features {
    enable-preview-commands = yes
    enable-testing-commands = yes
  }

  parameters {
    non-standard-config = yes
  }

  sequencers {
    sequencer1 {
      storage = ${_storage} {
        config.properties.databaseName = canton_sequencer
      }
      public-api {
        address = "0.0.0.0"
        port = 5001
      }
      admin-api {
        address = "0.0.0.0"
        port = 5002
      }
      sequencer.type = BFT
    }
  }

  mediators {
    mediator1 {
      storage = ${_storage} {
        config.properties.databaseName = canton_mediator
      }
      admin-api {
        address = "0.0.0.0"
        port = 5202
      }
    }
  }

  participants {
    participant1 {
      storage = ${_storage} {
        config.properties.databaseName = canton_participant
      }

      admin-api {
        address = "0.0.0.0"
        port = 5012
      }

      ledger-api {
        address = "0.0.0.0"
        port = 5011
        max-token-lifetime = Inf
        admin-token-config.admin-claim = true
        auth-services = [{
          type = unsafe-jwt-hmac-256
          target-audience = ${CANTON_AUTH_AUDIENCE}
          secret = ${CANTON_AUTH_SECRET}
        }]
        user-management-service.additional-admin-user-id = ${CANTON_ADMIN_USER_ID}
        interactive-submission-service {
          enable-verbose-hashing = true
        }
      }

      http-ledger-api {
        address = "0.0.0.0"
        port = 7575
      }

      monitoring.http-health-server {
        address = "0.0.0.0"
        port = 7000
      }
    }
  }
}
